apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-acyvndby
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-acyvndby:72293e521a88d414b44b18a9b6bc19301c508f7a
          name: container-image
